=== hrushikeshkothem/GitOps-Starter-Template-for-Scalable-Backends-with-ArgoCD-K8s/bootstrap/schema.config.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "required": ["host", "default_password", "sshPath", "roles", "accounts"],
    "properties": {
      "host": {
        "type": "string"
      },
      "default_password": {
        "type": "string"
      },
      "sshPath": {
        "type": "string",
        "pattern": "^/.+/.+"
      },
      "roles": {
        "type": "array",
        "items": {
          "type": "object",
          "required": ["name", "description", "policies", "groups"],
          "properties": {
            "name":          { "type": "string" },
            "description":   { "type": "string" },
            "policies": {
              "type": "array",
              "items": { "type": "string" }
            },
            "groups": {
              "type": "array",
              "items": { "type": "string" }
            }
          }
        }
      },
      "accounts": {
        "type": "array",
        "items": {
          "type": "object",
          "required": ["name", "group", "access"],
          "properties": {
            "name":   { "type": "string" },
            "group":  { "type": "string" },
            "access": { "type": "string", "enum": ["login"] }
          }
        }
      }
    },
    "additionalProperties": false
  }

=== hrushikeshkothem/GitOps-Starter-Template-for-Scalable-Backends-with-ArgoCD-K8s/bootstrap/config.json
{
    "host": "argocd.hrushispace.com",
    "default_password": "password1234",
    "sshPath": "/home/username/.ssh/argo_key",
    "roles":[
        {
            "name": "dev",
            "description": "Access to all application",
            "policies": [
                "p, proj:hrushispace:dev, applications, *, hrushispace/*, allow",
                "p, proj:hrushispace:dev, applications, delete, hrushispace/root-application, deny",
                "p, proj:hrushispace:dev, applications, delete, hrushispace/dev-cluster, deny"
            ],
            "groups": [
                "teamA-dev"
            ]
        },
        {
            "name": "infra",
            "description": "Access to all application and repositories",
            "policies": [
                "p, proj:hrushispace:infra, repositories, *, hrushispace/*, allow",
                "p, proj:hrushispace:infra, applications, *, hrushispace/*, allow",
                "p, proj:hrushispace:infra, applications, delete, hrushispace/root-application, deny"
            ],
            "groups": [
                "teamA-infra"
            ]
        }
    ],
    "accounts": [
        {
            "name": "X",
            "group": "teamA-dev",
            "access": "login"
        },
        {
            "name": "Y",
            "group": "teamA-infra",
            "access": "login"
        }
    ]
}
